parameters:
#    cl_symfony_doctrine_search_functions.example.class: CL\SymfonyDoctrineSearchFunctionsBundle\Example

services:
#    cl_symfony_doctrine_search_functions.example:
#        class: %cl_symfony_doctrine_search_functions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
